apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      labels:
        app: payments-ms
    spec:
      imagePullSecrets:
      - name: gcregistery-json-key
      containers:
      - image: northamerica-south1-docker.pkg.dev/tienda-ms-485104/image-registry/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3006"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:3006/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:3006/payments/cancel"
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret
        - name: STRIPE_ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpoint_secret
        resources: {}
status: {}
