apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      labels:
        app: products-ms
    spec:
      imagePullSecrets:
      - name: gcregistery-json-key
      containers:
      - image: northamerica-south1-docker.pkg.dev/tienda-ms-485104/image-registry/products-ms
        name: products-ms
        env:
        - name: PORT
          value: "3006"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          value: "file:./dev.db"
        resources: {}
status: {}
